[fix] added manylinux support (#185)
- [x] fix the build error for cuda 11.8
- [ ] add cuda 11.8 support for manylinux


/usr/local/cuda/bin/../targets/x86_64-linux/include/crt/host_config.h:132:2:
error: #error -- unsupported GNU version! gcc versions later than 11 are
not supported! The nvcc flag '-allow-unsupported-compiler' can be used
to override this version check; however, using an unsupported host
compiler may cause compilation failure or incorrect run time execution.
Use at your own risk.
132 | #error -- unsupported GNU version! gcc versions later than 11 are
not supported! The nvcc flag '-allow-unsupported-compiler' can be used
to override this version check; however, using an unsupported host
compiler may cause compilation failure or incorrect run time execution.
Use at your own risk.